// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Typhoon.Respository.Context;

#nullable disable

namespace Typhoon.Respository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Typhoon.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7531),
                            Deleted = false,
                            Description = "Television Category",
                            Name = "Television"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7545),
                            Deleted = false,
                            Description = "Mobile Phone Category",
                            Name = "Mobile Phone"
                        });
                });

            modelBuilder.Entity("Typhoon.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7681),
                            Deleted = false,
                            Description = "Samsung Galaxy A04s 64 GB 4 GB Ram (Samsung Türkiye Garantili)",
                            Name = "Samsung Galaxy A04S",
                            Price = 5300m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7688),
                            Deleted = false,
                            Description = "Samsung Galaxy A54 256 GB 8 GB Ram (Samsung Türkiye Garantili)",
                            Name = "Samsung Galaxy A54",
                            Price = 16660m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7689),
                            Deleted = false,
                            Description = "Samsung Galaxy S24 Ultra 512 GB 12 GB Ram (Samsung Türkiye Garantili)",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 69999m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7691),
                            Deleted = false,
                            Description = "Samsung Galaxy S23 Ultra 512 GB 12 GB Ram (Samsung Türkiye Garantili)",
                            Name = "Samsung Galaxy S23 Ultra",
                            Price = 57599m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Apple",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7692),
                            Deleted = false,
                            Description = "iPhone 15 Pro Max 512 GB",
                            Name = "iPhone 15 Pro",
                            Price = 85699m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Apple",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7694),
                            Deleted = false,
                            Description = "iPhone 13 Pro Max 512 GB",
                            Name = "iPhone 13 Pro Max",
                            Price = 74999m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Apple",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7695),
                            Deleted = false,
                            Description = "iPhone 14 Plus 128 GB",
                            Name = "iPhone 14 Plus",
                            Price = 48749m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7696),
                            Deleted = false,
                            Description = "Samsung 65QN85C 65\" 163 Ekran Uydu Alıcılı 4K Ultra HD Smart Neo QLED TV",
                            Name = "Samsung 65QN85C",
                            Price = 61099m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7698),
                            Deleted = false,
                            Description = "Samsung 55CU8000 55\" 138 Ekran Uydu Alıcılı Crystal 4K Ultra HD Smart LED TV",
                            Name = "Samsung 55CU8000",
                            Price = 25379m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "LG",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7699),
                            Deleted = false,
                            Description = "LG OLED65CS3VA 65\" 165 Ekran Uydu Alıcılı 4K Ultra HD webOS Smart OLED TV ",
                            Name = "LG OLED65CS3VA",
                            Price = 69799m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "LG",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 2, 5, 21, 33, 51, 950, DateTimeKind.Local).AddTicks(7701),
                            Deleted = false,
                            Description = "LG 65QNED756 65\" 165 Ekran Uydu Alıcılı 4K Ultra HD webOS Smart QNED TV",
                            Name = "LG 65QNED756",
                            Price = 44513m
                        });
                });

            modelBuilder.Entity("Typhoon.Domain.Entities.Product", b =>
                {
                    b.HasOne("Typhoon.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Typhoon.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
